- name: "DeepSeek-R1-Distill-Llama-8B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Llama-8B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "DeepSeek-R1-Distill-Qwen-7B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Qwen-7B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:


- name: "DeepSeek-R1-Distill-Qwen-14B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Qwen-14B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:


- name: "DeepSeek-V2-Lite"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-V2-Lite"
  tp: 1
  dp: 1
  pp: 1
  extra_args:
    --chat-template: chat_template/tool_chat_template_deepseekr1.jinja

- name: "DeepSeek-R1-BF16-L4-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-BF16-L4-W8A8"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Baichuan-7B"
  model_path: "/mxstorage/pde_ai/models/llm/Baichuan/Baichuan-7B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:
    --chat-template: chat_template/template_baichuan.jinja

- name: "Baichuan2-7B-Chat"
  model_path: "/mxstorage/pde_ai/models/llm/Baichuan/Baichuan2-7B-Chat"
  tp: 1
  dp: 1
  pp: 1
  extra_args:
    --chat-template: chat_template/template_baichuan.jinja

- name: "ChatGLM3-6B"
  model_path: "/mxstorage/pde_ai/models/llm/ChatGLM/chatglm3-6b"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "GLM-4-9B-Chat"
  model_path: "/mxstorage/pde_ai/models/llm/ChatGLM/glm-4-9b-chat"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "GLM-4v-9B"
  model_path: "/mxstorage/pde_ai/models/llm/ChatGLM/glm-4v-9b"
  tp: 1
  dp: 1
  pp: 1
  extra_args:
    --hf-overrides: "\"architectures\":[\"GLM4VForCausalLM\"]}"

- name: "InternVL2_5-8B"
  model_path: "/mxstorage/pde_ai/models/llm/Internlm/InternVL2_5-8B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "internlm3-8b-instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Internlm/internlm3-8b-instruct"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "InternVL2-8B"
  model_path: "/mxstorage/pde_ai/models/llm/Internlm/InternVL2-8B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Llama-2-7B-hf"
  model_path: "/mxstorage/pde_ai/models/llm/Llama/Llama-2-7b-hf"
  tp: 1
  dp: 1
  pp: 1
  extra_args:


- name: "Qwen2.5-VL-7B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2.5-VL-7B-Instruct"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen2-VL-7B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2-VL-7B-Instruct"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen2.5-72B-Instruct-AWQ"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2___5-72B-Instruct-AWQ"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen2.5-72B-Instruct-GPTQ"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2___5-72B-Instruct-GPTQ-Int4"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen2.5-14B-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/W8A8/Qwen2.5-14B-Instruct-W8A8-Dynamic-Per-Token"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-14B-AWQ"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-14B-AWQ"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-14B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-14B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-30B-A3B-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-30B-A3B.w8a8"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-32B-AWQ"
  model_path: "/pde_ai/models/llm/Qwen/Qwen3-32B-AWQ"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-4B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-4B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-8B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-8B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-1.7B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-1___7B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-VL-8B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-VL-8B-Instruct"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: Qwen3-VL-30B-A3B-Instruct_W8A8
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-VL-30B-A3B-Instruct_W8A8/vllm_quant_model"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name : "Qwen3-VL-4B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-VL-4B-Instruct"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-VL-8B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-VL-8B-Instruct"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-0.6B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-0.6B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen2.5-1.5B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2___5-1___5B-Instruct"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-Reranker-8B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-Reranker-8B"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Hunyuan-0.5B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Hunyuan/Hunyuan-0.5B-Instruct"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "Hunyuan-7B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Hunyuan/Hunyuan-7B-Instruct"
  tp: 1
  dp: 1
  pp: 1
  extra_args:

- name: "PaddleOCR-VL"
  model_path: "/mxstorage/pde_ai/models/llm/PaddleOCR-VL"
  tp: 1
  dp: 1
  pp: 1
  is_multimodal: true
  extra_args:

- name: "Qwen2-72B-Instruct-w8a8"
  model_path: "/mxstorage/pde_ai/models/llm/W8A8/Qwen2-72B-Instruct-quantized___w8a8"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-30B-A3B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-30B-A3B"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-32B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-32B"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-Next-80B-A3B-Instruct.w8a8"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-Next-80B-A3B-Instruct.w8a8"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-Omni-30B-A3B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-Omni-30B-A3B-Instruct"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-VL-30B-A3B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-VL-30B-A3B-Instruct"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "Meta-Llama-3-70B-Instruct-w8a8"
  model_path: "/mxstorage/pde_ai/models/llm/W8A8/Meta-Llama-3-70B-Instruct-quantized___w8a8"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "ERNIE-4.5-21B-A3B-PT"
  model_path: "/mxstorage/pde_ai/models/llm/ERNIE/ERNIE-4.5-21B-A3B-PT"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "InternVL2_5-26B"
  model_path: "/mxstorage/pde_ai/models/llm/Internlm/InternVL2_5-26B"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "internlm3-8b-instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Internlm/internlm3-8b-instruct"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "Kimi-Linear-48B-A3B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Kimi-Linear-48B-A3B-Instruct"
  tp: 2
  dp: 1
  pp: 1
  extra_args:

- name: "Mixtral-8x7B-v0.1"
  model_path: "/mxstorage/pde_ai/models/llm/Mistral/Mixtral-8x7B-v0.1"
  tp: 4
  dp: 1
  pp: 1
  extra_args:

- name: "QwQ-32B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/QwQ-32B"
  tp: 4
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen2.5-72B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2.5-72B-Instruct"
  tp: 4
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-32B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-32B"
  tp: 4
  dp: 1
  pp: 1
  extra_args:


- name: "Qwen3-Next-80B-A3B-Instruct.w8a8"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-Next-80B-A3B-Instruct.w8a8"
  tp: 4
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-Next-80B-A3B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-Next-80B-A3B-Instruct"
  tp: 4
  dp: 1
  pp: 1
  extra_args:

- name: "DeepSeek-R1-Distill-Llama-70B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Llama-70B"
  tp: 4
  dp: 1
  pp: 1
  extra_args:

- name: "DeepSeek-R1-Distill-Qwen-32B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Qwen-32B"
  tp: 4
  dp: 1
  pp: 1
  extra_args:

- name: "Meta-Llama-3-70B"
  model_path: "/mxstorage/pde_ai/models/llm/Llama/Meta-Llama-3-70B"
  tp: 4
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-30B-A3B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-30B-A3B"
  tp: 2
  dp: 2
  pp: 1
  extra_args:

- name: "Qwen3-32B"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-32B"
  tp: 2
  dp: 2
  pp: 1
  extra_args:

- name: "DeepSeek-R1-Distill-Llama-70B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Llama-70B"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

- name: "DeepSeek-R1-Distill-Qwen-32B"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-Distill-Qwen-32B"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

- name: "DeepSeek-R1-L12-BF16"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-L12-BF16"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

- name: "DeepSeek-R1-awq"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-awq"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

# - name: "DeepSeek-R1-BF16-L4-W8A8"
#   model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-BF16-L4-W8A8"
#   tp: 4
#   dp: 2
#   pp: 1
#   dcp: 2
#   gpu_memory_utilization: 0.8
#   extra_args:

- name: "DeepSeek-R1-BF16-L4-W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/DeepSeek/DeepSeek-R1-BF16-L4-W8A8"
  tp: 4
  dp: 2
  pp: 1
  dcp: 2
  gpu_memory_utilization: 0.8
  extra_args:

- name: "Qwen2.5-72B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2.5-72B-Instruct"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-235B-A22B-w8a8"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-235B-A22B.w8a8"
  tp: 8
  dp: 1
  pp: 1
  extra_args:
  
- name: "QwQ-32B-Preview"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/QwQ-32B"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-Next-80B-A3B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-Next-80B-A3B-Instruct"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen2.5-VL-72B-Instruct"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen2.5-VL-72B-Instruct"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

- name: "Qwen3-VL-235B-A22B-Instruct_W8A8"
  model_path: "/mxstorage/pde_ai/models/llm/Qwen/Qwen3-VL-235B-A22B-Instruct_W8A8/vllm_quant_model"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

- name: "InternVL3-78B"
  model_path: "/mxstorage/pde_ai/models/llm/Internlm/InternVL3-78B"
  tp: 8
  dp: 1
  pp: 1
  extra_args:

- name: "Mixtral-8x22B-Instruct-v0.1"
  model_path: "/mxstorage/pde_ai/models/llm/Mistral/Mixtral-8x22B-Instruct-v0.1"
  tp: 8
  dp: 1
  pp: 1
  extra_args:
